<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\App.Core\App.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  <RootNamespace>SmartNetworkTrafficAnalyzer.Infrastructure</RootNamespace>
  <AssemblyName>SmartNetworkTrafficAnalyzer.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="data\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
